config/routes.rb
Mabel::Application.routes.draw do

  devise_for :users,
  :controllers => {
    :invitations   => "users/invitations",
    :passwords     => "users/passwords",
    :registrations => "users/registrations",
    :sessions      => "users/sessions"
  }

  namespace :users do
    resources :beta_requests, :only => [:index, :new, :create] do
      put :invite, :on => :member
    end
  end

  namespace :admin do 
    resources :users
  end

  resources :ingredients
  
  resources :meal_plans, :except => :show do
    resources :planned_meals
    resource :shopping_list, :only => :show
  end

  post "/current_meal_plan/add_recipe/:id", to: "current_meal_plan#add_recipe", :as => :current_meal_plan_add_recipe
  get "current_meal_plan/edit"           => "current_meal_plan#edit",       :as => :edit_current_meal_plan
  
  resources :recipes do
    get :autocomplete_for_ingredient_amount_unit, :on => :collection
    get :autocomplete_for_ingredient_name,        :on => :collection
    get :autocomplete_for_recipe_name,            :on => :collection
  end

  resources :recipe_finders, :only => [:new, :show, :update] do
    resources :finder_ingredients
    get :autocomplete_for_ingredient_name, :on => :collection
  end

  root :to => "home#index"

  get "*path" => "home#error"
end

app/models/meal_plan.rb
class MealPlan < ActiveRecord::Base

  has_many :planned_meals
  has_many :recipes, :through => :planned_meals
  belongs_to :user
  
  default_scope -> { order 'created_at DESC' }

  after_initialize :set_defaults

  def self.user_plans(user)
    where(:user_id => user)
  end
    
  def self.default_name
    "Week of #{Date.today.monday.readable_inspect}"
  end

  def set_defaults
    self.name ||= MealPlan.default_name
  end

  def populate_shopping_list
    recipes.inject(ShoppingList.new) do |shopping_list, recipe|
      recipe.ingredient_amounts.inject(shopping_list) do |shopping_list, ingredient_amount|
        shopping_list.add(ingredient_amount)
      end
    end
  end

end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController
  load_and_authorize_resource
  
  def create
    if demo_mode_active?
      flash.now[:alert] = "Sign up if you'd like to create and edit meal plans"
      render :action => "new" and return false
    end

    if @meal_plan.save
      set_current_meal_plan_if_selected(params)
      redirect_to edit_meal_plan_path(@meal_plan), :notice => "Your meal plan is ready for some recipes"
    else
      flash.now[:alert] = "Sorry, we could not save your meal plan"
      render :action => "new"
    end
  end

  def update
    if demo_mode_active?
      flash.now[:alert] = "Sign up if you'd like to create and edit meal plans"
      render :action => "edit" and return false
    end

    if @meal_plan.update_attributes(params[:meal_plan])
      set_current_meal_plan_if_selected(params)
      redirect_to edit_meal_plan_path(@meal_plan), :notice => "Your meal plan is ready for some recipes"
    else
      flash.now[:alert] = "Sorry, we could not save your meal plan"
      render :action => "edit"
    end
  end

  def set_current_meal_plan_if_selected(params)
    current_user.update_attribute('current_meal_plan', @meal_plan) if params[:current_meal_plan] == 'yes'
  end

end

app/helpers/meal_plans_helper.rb
module MealPlansHelper

  def current_meal_plan
    current_user.current_meal_plan if current_user
  end

  def current_meal_plan?(meal_plan)
    meal_plan == current_meal_plan
  end

end

app/views/meal_plans/_form.html.haml
= form_for @meal_plan do |form|
  = render "shared/error_messages", :target => @meal_plan

  = form.hidden_field :user_id, :value => current_user.id

  %section
    %h3= form.label :name, "Give this meal plan a name"
    = form.text_field :name

  %section
    = label_tag :current_meal_plan, 'Make this your current meal plan'
    = check_box_tag :current_meal_plan, 'yes', current_meal_plan?(@meal_plan) || @meal_plan.new_record?

  %section
    = form.submit submit_text

%section
  %h3 Planned meals
  - if @meal_plan.planned_meals.empty?
    %p You don't have any meals in this plan yet.  Find a recipe you like and add it.
  - else
    %ul
      - @meal_plan.planned_meals.each do |planned_meal|
        %li
          =link_to planned_meal.recipe.name, recipe_path(planned_meal.recipe)
          %span=button_to 'remove', meal_plan_planned_meal_path(@meal_plan, planned_meal), :method => :delete, :title => 'remove'

app/views/meal_plans/edit.html.haml
- meal_plans_menu << MenuLink.new('Shopping list', meal_plan_shopping_list_path(@meal_plan)) unless @meal_plan.planned_meals.empty?

= render :partial => "form", :locals => { :submit_text => 'Save this meal plan' }

app/views/meal_plans/index.html.haml
- if @meal_plans.empty?
  %h1 You don't currently have any meal plans.  
  %p Once you've started a new meal plan, you'll be able to add recipes to it.

- else
  %h1 My Meal Plans
   
  %section
    %ul
      - @meal_plans.each do |meal_plan|
        %li{:id => current_meal_plan?(meal_plan) ? "current_meal_plan" : nil}= link_to meal_plan.name, edit_meal_plan_path(meal_plan)
   
  %section
    = image_tag '/images/arrow.gif'
    Indicates your current meal plan.  You are adding recipes to this plan.

app/views/meal_plans/new.haml
.meal_plan
  %h2= "Plan for #{@meal_plan.name}"

  - @meal_plan.planned_meals.each do |planned_meal|
    .planned_meal{ :id => "#{planned_meal.day}" }
      %h3= planned_meal.day
      .recipe= planned_meal.recipe.name

app/views/meal_plans/new.html.haml
.meal_plan
  %h2= "Plan for #{@meal_plan.name}"

  - @meal_plan.planned_meals.each do |planned_meal|
    .planned_meal{ :id => "#{planned_meal.day}" }
      %h3= planned_meal.day
      .recipe= planned_meal.recipe.name

app/views/meal_plans/show.haml
.meal_plan
  %h2= @meal_plan.name

  - @meal_plan.planned_meals.group_by(&:day).each do |day, planned_meals|
    .planned_day{ :id => "#{day}" }
      %h3= day
      %ul
        - planned_meals.each do |planned_meal|
          %li.recipe
            = planned_meal.recipe.name
            = link_to 'Suggest Another', suggest_meal_plan_planned_meal_path(@meal_plan, planned_meal)