config/routes.rb
Mabel::Application.routes.draw do

  devise_for :users,
  :controllers => {
    :invitations   => "users/invitations",
    :passwords     => "users/passwords",
    :registrations => "users/registrations",
    :sessions      => "users/sessions"
  }

  namespace :users do
    resources :beta_requests, :only => [:index, :new, :create] do
      put :invite, :on => :member
    end
  end

  namespace :admin do 
    resources :users
  end

  resources :ingredients
  
  resources :meal_plans, :except => :show do
    resources :planned_meals
    resource :shopping_list, :only => :show
  end

  post "/current_meal_plan/add_recipe/:id", to: "current_meal_plan#add_recipe", :as => :current_meal_plan_add_recipe
  get "current_meal_plan/edit"           => "current_meal_plan#edit",       :as => :edit_current_meal_plan
  
  resources :recipes do
    get :autocomplete_for_ingredient_amount_unit, :on => :collection
    get :autocomplete_for_ingredient_name,        :on => :collection
    get :autocomplete_for_recipe_name,            :on => :collection
  end

  resources :recipe_finders, :only => [:new, :show, :update] do
    resources :finder_ingredients
    get :autocomplete_for_ingredient_name, :on => :collection
  end

  root :to => "home#index"

  get "*path" => "home#error"
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  belongs_to :user
  
  has_many :ingredient_amounts, -> { order :position }, :dependent => :destroy
  has_many :ingredients, :through => :ingredient_amounts

  accepts_nested_attributes_for :ingredient_amounts,
  :reject_if => lambda { |a| a[:ingredient_attributes][:name].blank? },
  :allow_destroy => true

  validates_presence_of :name, :directions

  def self.named_like(name)
    where { |i| i.name.like "%#{name}%" }
  end

  def self.recently_added
    order('created_at DESC').limit(5)
  end

  def self.recently_edited
    order('updated_at DESC').limit(5)
  end
  
  scope :with_ingredient, lambda { |ingredient| joins(:ingredients).where { |i| i.name =~ "%#{ingredient}%" } }

  before_save :sequence_ingredient_amounts

  def next
    Recipe.where('name > ?', name).order('name ASC').limit(1).first
  end

  def previous
    Recipe.where('name < ?', name).order('name DESC').limit(1).first
  end

  def self.with_ingredients(ingredients)
    recipe_collections = ingredients.map { |ingredient| self.with_ingredient(ingredient).load }
    recipe_collections.inject { |recipes, next_set| recipes & next_set }.uniq
  end

  def sequence_ingredient_amounts
    ingredient_amounts.each_with_index do |ingredient_amount, index|
      ingredient_amount.insert_at(ingredient_amount.position || index + 1)
    end
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :authenticate_user!
  
  autocomplete_for :ingredient_amount, :unit
  autocomplete_for :ingredient, :name
  autocomplete_for :recipe, :name
  
  def index
    if params[:user] == "me"
      @recipes = current_user.recipes
    else
      @recipes = Recipe.order('name ASC')
    end
    @recipes = @recipes.named_like(params[:name])
  end

  def new
    @recipe = Recipe.new
    3.times { @recipe.ingredient_amounts.build }
  end

  def create
    @recipe = Recipe.new(params[:recipe])
    @recipe.user = current_user

    if demo_mode_active?
      flash.now[:alert] = "Sign up if you'd like to create and edit recipes"
      render :action => "new" and return false
    end

    if @recipe.save
      redirect_to @recipe, :notice => "Thank you for adding that new recipe"
    else
      flash.now[:alert] = "Sorry, we could not save your recipe"
      render :action => "new"
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @recipe.ingredient_amounts.each_with_index do |ingredient_amount, index|
      ingredient_amount.update_attributes(:position => index + 1)
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if demo_mode_active?
      flash.now[:alert] = "Sign up if you'd like to create and edit recipes"
      render :action => "edit" and return false
    end

    if @recipe.update_attributes(params[:recipe])
      redirect_to recipe_path(@recipe), :notice => "Thank you for editing that recipe"
    else
      render :action => 'edit'
    end
  end

end

app/views/recipes/_form.html.haml
= javascript_include_tag "wmd/showdown.js"

= form_for @recipe, :builder => DemoFormBuilder do |form|
  = render "shared/error_messages", :target => @recipe

  %section
    %h2= form.label :name, "Enter the name of the recipe"
    = form.text_field :name

  %section
    %h2= form.label :description, "How would you describe this recipe? Maybe there's a story behind it?"
    = form.text_area :description

  %section
    %h2 Ingredients
    %table
      %thead
        %tr
          %th #
          %th Amount
          %th Unit
          %th Name
      = form.fields_for :ingredient_amounts, @recipe.ingredient_amounts do |ingredient_amount_form|
        = render "ingredient_amount_fields", :builder => ingredient_amount_form
    = link_to "Add an ingredient", "/#", id: "add-ingredient"

  %section
    %h2= form.label :directions, "Enter the directions"
    #wmd-button-bar
    = form.text_area :directions, :id => "wmd-input"
    #wmd-preview

  %section
    = form.submit submit_text

= enable_wmd :buttons => "bold italic | ol ul heading hr"

app/views/recipes/_ingredient_amount_fields.html.haml
%tr.ingredient
  %td.number
    = builder.text_field :position
  %td.amount
    = builder.text_field :amount
  %td.unit
    = builder.text_field :unit, :class => 'autocomplete', 'data-autocomplete-url' => autocomplete_for_ingredient_amount_unit_recipes_path
  %td.name
    = builder.fields_for :ingredient do |ingredient_form|
      = ingredient_form.text_field :name, :class => 'autocomplete', 'data-autocomplete-url' => autocomplete_for_ingredient_name_recipes_path
  %td
    = link_to 'remove', '/#', class: 'remove-ingredient'

app/views/recipes/edit.html.haml
- recipes_menu << MenuLink.new('Discard edits', recipe_path(@recipe))

= render :partial => "form", :locals => { :submit_text => 'Save your edits' }

app/views/recipes/index.haml
- define_actions 'Add a new recipe' => new_recipe_path

%h2 Recipes
%ul
  - @recipes.each do |recipe|
    %li= link_to recipe.name, recipe_path(recipe)

app/views/recipes/index.html.haml
%h1 Recipes

- if @recipes.empty?
  %p You haven't created any recipes yet.  

  %p
    Please use the 
    %strong 'Add a new recipe' 
    link on the 
    %strong Recipes
    menu to the left of the page.

- else
  %section
    = form_tag recipes_path, :method => :get do
      %fieldset#search_form
        %p
          = label_tag :name, "To search, enter part of a recipe name below"
          %i (leave blank to list all recipes)
          %br
          = text_field_tag :name, params[:name], :class => 'autocomplete', 'data-autocomplete-url' => autocomplete_for_recipe_name_recipes_path
          = submit_tag 'Search for recipes', :name => nil
   
  %section
    %ul
      - @recipes.each do |recipe|
        %li= link_to recipe.name, recipe_path(recipe)

app/views/recipes/new.html.haml
= render :partial => "form", :locals => { :submit_text => 'Save new recipe' }

app/views/recipes/show.haml
- define_actions 'Edit this recipe' => edit_recipe_path(@recipe)

.recipe
  %h2= @recipe.name

  .ingredients
    %h3 Ingredients
    %ul
      - @recipe.ingredient_amounts.each do |ingredient_amount|
        %li= "#{ingredient_amount.amount} #{ingredient_amount.unit} #{ingredient_amount.ingredient.name}"
        
  .directions
    %h3 Directions
    %p= @recipe.directions

app/views/recipes/show.html.haml
- recipes_menu << MenuLink.new('Edit this recipe', edit_recipe_path(@recipe))
- recipes_menu << MenuButton.new('Add to Meal Plan', current_meal_plan_add_recipe_path(@recipe))

%nav
  Browse to 
  = link_to "Previous", recipe_path(@recipe.previous)
  or
  = link_to "Next", recipe_path(@recipe.next)
  Recipe

%section#recipe
  %h1= @recipe.name
  %p= @recipe.description

  %section#ingredients
    %h2 Ingredients
    %ul
      - @recipe.ingredient_amounts.each do |ingredient_amount|
        %li= "#{ingredient_amount.amount} #{ingredient_amount.unit} #{ingredient_amount.ingredient.name}"
        
  %section#directions
    %h2 Directions
    :markdown
      #{@recipe.directions}