config/routes.rb
Mabel::Application.routes.draw do

  devise_for :users,
  :controllers => {
    :invitations   => "users/invitations",
    :passwords     => "users/passwords",
    :registrations => "users/registrations",
    :sessions      => "users/sessions"
  }

  namespace :users do
    resources :beta_requests, :only => [:index, :new, :create] do
      put :invite, :on => :member
    end
  end

  namespace :admin do 
    resources :users
  end

  resources :ingredients
  
  resources :meal_plans, :except => :show do
    resources :planned_meals
    resource :shopping_list, :only => :show
  end

  post "/current_meal_plan/add_recipe/:id", to: "current_meal_plan#add_recipe", :as => :current_meal_plan_add_recipe
  get "current_meal_plan/edit"           => "current_meal_plan#edit",       :as => :edit_current_meal_plan
  
  resources :recipes do
    get :autocomplete_for_ingredient_amount_unit, :on => :collection
    get :autocomplete_for_ingredient_name,        :on => :collection
    get :autocomplete_for_recipe_name,            :on => :collection
  end

  resources :recipe_finders, :only => [:new, :show, :update] do
    resources :finder_ingredients
    get :autocomplete_for_ingredient_name, :on => :collection
  end

  root :to => "home#index"

  get "*path" => "home#error"
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

  validates_presence_of :name
  
  default_scope -> { order 'name ASC' }

  Unit = {
    'tablspoon'  => 'tablespoon',
    'tbs.'       => 'tablespoon',
    'tbsp.'      => 'tablespoon',
    'tsp.'       => 'teaspoon',
    'lb.'        => 'pound',
    'lbs.'       => 'pound',
    'oz.'        => 'ounce',
    'whole head' => 'head'
  }
  
  def remove_unit_from_name
    self.name =~ /^(clove|cup|dash|drop|whole head|head|ounce|oz.|pint|lbs?.|pound|sprig|stalk|stick|table?spoon|tbsp?.|teaspoon|tsp.)s? +(.*)/
    unit_in_name = Unit[$1] || $1
    name = $2
    
    self.update_attributes(:name => name) if unit_in_name
    return unit_in_name
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(params[:ingredient])

    if @ingredient.save
      flash[:notice] = 'Ingredient was successfully created.'
      redirect_to ingredients_url
    else
      render :action => :new
    end

  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])

    if @ingredient.update_attributes(params[:ingredient])
      flash[:notice] = 'Ingredient was successfully updated.'
      redirect_to ingredients_url
    else
      render :action => :edit
    end

  end

end

app/views/ingredients/_form.haml
= form_for @ingredient do |form|
  = form.label :name, 'Enter the name of the ingredient'
  = form.text_field :name, :id => :name
  - if @ingredient.errors.any?
    .errorExplanation
      %h2 The following errors prohibited this form from being saved:
      %ul
        - @ingredient.errors.full_messages.each do |msg|
          %li=msg

  = form.submit 'Submit'

app/views/ingredients/_form.html.haml
= form_for @ingredient do |form|
  = render "shared/error_messages", :target => @ingredient

  = form.label :name, 'Enter the name of the ingredient'
  = form.text_field :name, :id => :name

  = form.submit 'Submit'

app/views/ingredients/edit.haml
%h1 Editing Ingredient

= render 'form'

app/views/ingredients/edit.html.haml
%h1 Editing Ingredient

= render 'form'

app/views/ingredients/index.haml
=link_to 'New', new_ingredient_path

- if @ingredients.empty? then
  No ingredients available yet.
- else
  %table
    %tr
      %th Ingredient
   
    - @ingredients.each do |ingredient|
      %tr
        %td= link_to ingredient.name, edit_ingredient_path(ingredient)

app/views/ingredients/index.html.haml
=link_to 'New', new_ingredient_path

- if @ingredients.empty? then
  No ingredients available yet.
- else
  %table
    %tr
      %th Ingredient
   
    - @ingredients.each do |ingredient|
      %tr
        %td= link_to ingredient.name, edit_ingredient_path(ingredient)

app/views/ingredients/new.haml
%h1 New Ingredient

= render :partial => 'form'

app/views/ingredients/new.html.haml
%h1 New Ingredient

= render :partial => 'form'