config/routes.rb
Mabel::Application.routes.draw do

  devise_for :users,
  :controllers => {
    :invitations   => "users/invitations",
    :passwords     => "users/passwords",
    :registrations => "users/registrations",
    :sessions      => "users/sessions"
  }

  namespace :users do
    resources :beta_requests, :only => [:index, :new, :create] do
      put :invite, :on => :member
    end
  end

  namespace :admin do 
    resources :users
  end

  resources :ingredients
  
  resources :meal_plans, :except => :show do
    resources :planned_meals
    resource :shopping_list, :only => :show
  end

  post "/current_meal_plan/add_recipe/:id", to: "current_meal_plan#add_recipe", :as => :current_meal_plan_add_recipe
  get "current_meal_plan/edit"           => "current_meal_plan#edit",       :as => :edit_current_meal_plan
  
  resources :recipes do
    get :autocomplete_for_ingredient_amount_unit, :on => :collection
    get :autocomplete_for_ingredient_name,        :on => :collection
    get :autocomplete_for_recipe_name,            :on => :collection
  end

  resources :recipe_finders, :only => [:new, :show, :update] do
    resources :finder_ingredients
    get :autocomplete_for_ingredient_name, :on => :collection
  end

  root :to => "home#index"

  get "*path" => "home#error"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def error
    render_home_with_message
  end

end

app/views/home/about.haml
%h2 About

app/views/home/index.haml
%h2 Welcome
%p We're here to help you plan meals for you and yours.  We really hope you love this site.
%p If you have an opinion on how it could be better, we'd love to hear from you.  Please submit your suggestions on the feedback forum which is available through the button on the right.

app/views/home/index.html.haml
%h1 Welcome
%p TastyPlans.com is here to help you plan meals for you and yours.  We really hope you love this site.
%p At some point we'll charge a monthly fee, but right now we'd like to offer a limited number of free registrations.
%p
  Please use the
  = link_to t("beta.request"), new_users_beta_request_path
  link at the top of the page if you'd like to sign up.  We won't charge you for your registration.

%h1 Help us help you
%p 
  = link_to "If you have an opinion on how TastyPlans could be better, we'd love to hear from you.  Please submit your suggestions on the feedback forum which is available at any time through the \"feedback\" button on the right ---->", 'http://tastyplans.uservoice.com/forums/81175', :class => 'contact_us'